services:
  database:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fiber_todo
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
    command: air
