services:
  database:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-fiber_todo}
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:postgres@database:5432/fiber_todo?sslmode=disable}
      TEST_DATABASE_URL: ${TEST_DATABASE_URL:-postgres://postgres:postgres@database:5432/fiber_todo_test?sslmode=disable}
    volumes:
      - .:/app
    command: air
